# -*- coding: utf-8 -*-
"""450Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AR4WMbXMl7PxAOQpqZRaJZRDnFIdj2Pw
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
st.title("Advertising Effectivness Saad")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X axis",["TV","radio","newspaper"])
y_var=st.sidebar.selectbox("Y axis",["sales"])

#show scatterplot
fig=px.scatter(df,x=x_var,y=y_var)
st.plotly_chart(fig)

#dataframe
st.write("### This is the data")
st.dataframe(df)

#SHow map
st.title("I'm the Map!!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',size='newspaper',
                      hover_name='City',color='sales',
                      color_continuous_scale=px.colors.sequential.Viridis)
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)